const header = document.getElementById('header')
header.style.backgroundColor= "green"
header.style.borderBottom="3px solid orange"
const hd = document.getElementById('main-heading')
hd.textContent= "Fruit World"
hd.style.color="orange"
const basketheading = document.getElementById('basket-heading')
basketheading.style.color="green"
const thanks= document.getElementById("thanks")
thanks.innerHTML="<p>Please visit us again</p>"